version: "3.7"

services:
  app:
    build: .
    container_name: my_go_app
    volumes:
      - .:/go/src/
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:9.4
    container_name: my_go_db
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go-project
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
    depends_on:
      - db
